### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by aron-net**
### In this feature branch we followed the project requirements:

- [x] Remove `current_user` method in `ApplicationController`, devise will provide us with one.
- [x]  [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [x]  [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling

### CODE REVIEW

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @aron-helu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


Screenshot from 2022-10-20 09-38-51


## Highlights :green_circle: 


- Correct Gitflow has been followed :heavy_check_mark: 
- PR has a good title and summary :heavy_check_mark: 
- No Linter error :heavy_check_mark: 


## Required Changes ♻️

- [ ] Hi @aron-helu, I got the error on the screenshot below when I tried to set up your app locally. Let's kindly fix :wrench: it. 

Screenshot from 2022-11-10 19-52-58


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Hannziegel** [comment]
> Hi @aron-helu ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> Screenshot from 2022-10-20 09-38-51
> 
> ## Highlights 🟢
> * Correct Gitflow has been followed ✔️
> * PR has a good title and summary ✔️
> * No Linter error ✔️
> 
> ## Required Changes ♻️
> * [ ]  Hi @aron-helu, I got the error on the screenshot below when I tried to set up your app locally. Let's kindly fix 🔧 it.
> 
> Screenshot from 2022-11-10 19-52-58
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello. @FrederickMih 
I don't have that problem on my side. But I think you forgot to add the migrations before the seed.
Try to use the commands as follow:
1º - ` rails db:drop `
2º - ` rails db:create `
3º - ` rails db:migrate `
4º - ` rails db:seed `
If this is the first time that you worked in the data base you don't need the first one.

**Comment by Hannziegel** [comment]
Hello @FrederickMih,
Thank you for your review!
But on my side is working as you can see here: 
image
image

But for this part of the project, we don't need to use the seeds. 
You have to start the server on your site, and test if the requirements are passing. The seed is not gonna work now because we are using the devise gem. So for you to add post or other things you have to sign in first. If you use the command `rails db:create` instead of the `rails db:setup` it should work. I could delete the old seed content and is gonna go back to work in the `db:setup` but I think then this should maybe be an optional suggestion. You can also read the indications that I pass in the read me file: 
image

**Comment by FrederickMih** [comment]
Hi @Hannziegel, I think you can't run the server without setting up the db which involves rails db:create, rails db:migrate. The command rails db:setup doesn't run the seed alone. Should I run rails server without running the migrations?. It doesn't work like that on my end. Check well the error on the screenshot.

**Comment by Hannziegel** [comment]
Hi @FrederickMih, yeah maybe you can create the `db:migrate` again. But what I had understood is that the migrate creates the schema that is gonna be used in the` db:create`, so you just need to create that one the first time. But either way, you also could do the `db:create` and then` db:migrate` before running the server. The problem now is the `db:seed` that is calling the functions of the old branch. But from what I understood in this branch we have to test the requirements like: Use the devise; Sign in with the user in the devise,; log out with the user; change password... So all those things I did as required and tested on my end. Did you tried ` rails db:drop`, `rails db:create`, `rails db:migrate` and then `rails start`? I can delete that file for the next part because I'm not gonna use `db:seed `anymore. But I think that should be an optional suggestion because it is not in the core requirements.

**Comment by FrederickMih** [comment]
Hi @Hannziegel , I understand. The next reviewer will be able to look into that.

**Comment by Hannziegel** [comment]
@FrederickMih Yeah, but thank you for appointing that out in the review 😃 , I'm certainly gonna remove that problem

**Review by bimbolabuari — COMMENTED** [review]
Hello @Hannziegel  👋,

_This is an additional review as a result of the second opinion request._

- The `db:setup` command runs a few processes:

   - Deletes all data, runs the migrations (updates the schema file) and initializes it with the seed data.
   `rails db:reset rails db:migrate rails db:seed`

- Currently, there seed data has a null value, therefore running `db:setup` might throw an error.



Screenshot 2022-11-11 at 01 58 21

Screenshot 2022-11-11 at 02 16 48


- The migration runs as expected.

Keep rocking 🚀!

**Review by BenMukebo — APPROVED** [review]
### Hi @aron-helu, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 



### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Devise has been installed and setup 👍🏻 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
